### ISSUE TITLE
Implement group method 

### ISSUE THREAD

**Issue by olga-demina** [pietrodev07/kittylog#11]
Add a new type of log that allows to group logs under the same label.
Example: https://www.w3schools.com/Jsref/met_console_group.asp

Possible usage:
kittylog.group(label, isCollapsed)
...
kittylog.groupEnd(label)

Example of output (here I use native console.group method)
![Schermata del 2024-01-29 15-07-48](https://github.com/pietrodev07/kittylog/assets/56634652/c5072c33-5aed-4fab-adad-042703d9c344)

If you like the idea, please, assign this issure to me.

**Comment by pietrodev07** [comment]
Yeah, it's a great idea! It also works in a nodejs execution?

**Comment by olga-demina** [comment]
Yes it works also in node js environment

**Comment by olga-demina** [comment]
I woud like to ask for an advise reguarding the feature in this issue.
I have implemented the basic feature of group log, everything works and I can see logs that belong to the group indented correctly. 
Now I would like also to group them visually by color. My idea is that the group name should have a color assigned randomly or by user's choice and then all the logs that belong to this group to have a sign "-" (dash) of the same color. 
I checked all the documentation and it seems that I can not get the group name from a log itself, so I have to keep it in a local data structure. 

So I have following situation:
- any log can belong to a group
- there can be nested groups
- every group has to have a color assigned

I was thinking about stack data structure, where every time a new console.group is called I would push the group color name and on every console.groupEnd I would pull the last group name (LIFO). 
So on every log called I should check if there is anything in the stack and if so I have to add the dash of the current color.

So my questions are:
1. Does it make sence to implement this feature (Though I like the idea of adding colors to the groups)?
2. Am I thinking in the right way?
3. Could anyone give me an advise on how to implement this kind of global store that contains the group stack?

Here is the screenshot to illustrate my idea:
![Group 8](https://github.com/pietrodev07/kittylog/assets/56634652/ca5a0ad1-3196-48c9-94e4-6544767273b7)

**Comment by alexandercerutti** [comment]
Hi @olga-demina, I'm here to help @pietrodev07, which asked me an opinion about your issue.

Although a stack (nothing more than an array, in the end) would probably be the most correct data structure to adopt, I have one main concern: having a _not-properly-handled_ global storage, might cause you in the future, where the storage is not emptied on the right moment and therefore you might find yourself in priting a log in the wrong subgroup, without the possibility to close it (you might not know the name).

Furthermore, how would you exactly render groups? I mean, `console.group` tells the devtools console to render a _collapsable_ block and I don't think there is a way to replicate the same mechanism.

My best guess is that the rendering side is something that should be handled by the devtools themselved, exactly through `console.group`.

The biggest issue here is how the logs are printed. The usage of special color-characters are not supported by all the dev tools.

https://github.com/pietrodev07/kittylog/blob/f5b2a178ef02ea0adf326dbf8dbf79eb8a7966aa/src/constants/index.ts#L2-L16

On Firefox and Safari, for example, using such string on `console.log`, result in this:

<img width="263" alt="immagine" src="https://github.com/pietrodev07/kittylog/assets/5442545/d345de0e-4f26-4037-b862-c2f77ccaf07d">

While in Chrome, it renders correctly:

<img width="222" alt="immagine" src="https://github.com/pietrodev07/kittylog/assets/5442545/4da434b2-0035-487e-b3cf-be69963c0e8a">

On the other way, using styling through CSS seems to be supported by all the major engines dev tools:

```
console.log("t0");
console.group("%c test", "background-color: #FFF");
	console.log("t1");
console.groupEnd("test")
console.log("t2")
```

<img width="469" alt="immagine" src="https://github.com/pietrodev07/kittylog/assets/5442545/95ff4aae-6df7-4d65-92e5-dc0c357fa001">

So, I'd leave all the rendering and enqueing mechanism to the browser, but I'd just add the colors through such CSS statements.

BTW, you can also do something like this:

<img width="487" alt="immagine" src="https://github.com/pietrodev07/kittylog/assets/5442545/c6650574-062e-4659-9c4f-50072e1c6925">

```javascript
console.log(`%c 🎨 Hey this is kitty log`, "background: linear-gradient(90deg,rgba(255, 0, 0, 0.7) 0%,rgba(255, 154, 0, 0.7) 10%,rgba(208, 222, 33, 0.7) 20%,rgba(79, 220, 74, 0.7) 30%,rgba(63, 218, 216, 0.7) 40%,rgba(47, 201, 226, 0.7) 50%,rgba(28, 127, 238, 0.7) 60%,rgba(95, 21, 242, 0.7) 70%,rgba(186, 12, 248, 0.7) 80%,rgba(251, 7, 217, 0.7) 90%,rgba(255, 0, 0, 0.7) 100%); padding: 10px; font-size: 2em")
```

@pietrodev07 I think you should support all the browsers, not just Chrome. We are not anymore in 2010-2014 where a site / tool gets optmized for just one browser / engine.

IMHO you might choose to use both `\x1b` when the you are running on a platform that supports something like an `stdout` (node, maybe bun?), otherwise attempt to use css.

Please note that when running logs through CI, logs are removed of their colors and therefore the all characters are printed as they are, both stdout and css modes. Might it be worth to add a clean passthrough mode for CI? Sometimes CIs offer some unstandardized globals that all implement, like `process.env.CI`.

Hope this helps.

**Comment by olga-demina** [comment]
Hi @alexandercerutti! 
Thank you so much for analyzing the issue and providing such a detailed response. Actually, the compatibility problem and the global state management problem were my biggest concerns. After reflecting on the functionality, I agree with you, and I've decided to stick with the browser implementation of this feature.

For Kittylog, I've implemented a kind of wrapper for this feature, and then the browser or Node environment will handle it.
Next will I will do the PR with my version.

It's interesting to consider the impact on CI. We should think about this scenario.

Thank you once again for your help!

**Comment by alexandercerutti** [comment]
@olga-demina I think @pietrodev07 will soon (if he already didn't) release a new version with a few changes about how colors are rendered. You might want to check if your PR works with them, to support CI and to not print at all the colors (I think).

@pietrodev07 did you perhaps already release the changes? If not, did you push the branch you were working on? So @olga-demina might check them and test the changes on it.

**Comment by pietrodev07** [comment]
@alexandercerutti @olga-demina I've just released changes about how colors are rendered. For now `browser` side and  `stdout` (node)!

**Comment by olga-demina** [comment]
@pietrodev07 Good job! I've just made the reset of my repo to your new version and actually I have to make a couple of changes to my implementation of this group function.
@alexandercerutti thank you for letting me know about it!
